services:
  - type: web
    name: cashjet-aviator
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PAYHERO_API_URL
        value: https://backend.payhero.co.ke/api/v2/payments
      - key: PAYHERO_CHANNEL_ID
        value: 10900
      - key: PAYHERO_API_USERNAME
        value: qI4IBCqJqR3mNGM9nqND
      - key: PAYHERO_API_PASSWORD
        value: GvWNypdtFlm8pVP4KXK2DdxIb0SUDrxtrtdrXnvP
      - key: PAYHERO_CALLBACK_URL
        value: https://yourdomain.com/api/payhero/callback
      - key: BASIC_AUTH_TOKEN
        value: Basic cUk0SUJDcUpxUjNtTkdNOW5xTkQ6R3ZXTnlwZHRGbG04cFZQNEtYSzJEZHhJYjBTVURyeHRydGRyWG52UA==
 
